services:

  todo:
    build: .
    container_name: todo
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - todo
    networks:
      - app-network
    restart: always

  # --- NEW: Log Viewer ---
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # read docker log
    ports:
      - "8888:8080"
    environment:
      - DOZZLE_LEVEL=info
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
